### ISSUE TITLE
Call to a member function addMessage() on null

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#276]
After upgrading to RC9, the following error prevents the application from loading anything in the main frame. This happens when installed from either git or composer.

```
Type: Error
Message: Call to a member function addMessage() on null
File: /var/www/phppgadmin-hf/src/traits/HelperTrait.php
Line: 73

#0 /var/www/phppgadmin-hf/src/classes/ContainerUtils.php(301): PHPPgAdmin\ContainerUtils->addFlash()
#1 /var/www/phppgadmin-hf/src/router.php(89): PHPPgAdmin\ContainerUtils->getDestinationWithLastTab()
#2 [internal function]: Closure->{closure}()
#3 /var/www/phppgadmin-hf/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#4 /var/www/phppgadmin-hf/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#5 /var/www/phppgadmin-hf/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke()
#6 /var/www/phppgadmin-hf/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
#7 /var/www/phppgadmin-hf/vendor/slim/slim/Slim/App.php(503): Slim\Route->run()
#8 /var/www/phppgadmin-hf/src/middleware/PopulateRequestResponse.php(82): Slim\App->__invoke()
#9 [internal function]: PHPPgAdmin\Middleware\PopulateRequestResponse->__invoke()
#10 /var/www/phppgadmin-hf/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#11 [internal function]: Slim\DeferredCallable->__invoke()
#12 /var/www/phppgadmin-hf/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#13 /var/www/phppgadmin-hf/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#14 /var/www/phppgadmin-hf/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#15 /var/www/phppgadmin-hf/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#16 /var/www/phppgadmin-hf/src/router.php(179): Slim\App->run()
#17 /var/www/phppgadmin-hf/index.php(45): require_once('/var/www/phppga...')
#18 {main}
```

**Comment by ffflabs** [comment]
I'm adding a check to skip calling said method if the container doesn't have a flash property. Released as v6.0.0
